name: JInput CI

on: [push, pull_request, workflow_dispatch]

jobs:
  build-natives:
    name: ${{ matrix.name }} natives build
    strategy:
      matrix:
        include:
          - name: Linux
            os: ubuntu-latest
            artifact: linux-natives
            project: plugins/linux
          - name: Windows
            os: windows-latest
            artifact: windows-natives
            project: plugins/windows
          - name: macOS
            os: macos-latest
            artifact: macos-natives
            project: plugins/OSX
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 16
          java-package: jdk

      - name: Setup MSVC Dev Cmd
        if: matrix.os == 'windows-latest'
        uses: ilammy/msvc-dev-cmd@v1

      - name: Build with Maven
        run: mvn --batch-mode --file pom.xml --also-make --projects ${{ matrix.project }} clean install

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact }}
          path: ${{ matrix.project }}/target/*.jar

  build:
    needs: build-natives
    name: Packaged build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 16
          java-package: jdk

      - name: Download linux natives
        uses: actions/download-artifact@v4
        with:
          name: linux-natives
          path: plugins/linux/target
      - name: Download macos natives
        uses: actions/download-artifact@v4
        with:
          name: macos-natives
          path: plugins/OSX/target
      - name: Download windows natives
        uses: actions/download-artifact@v4
        with:
          name: windows-natives
          path: plugins/windows/target
      - run: find . -name \*.jar