name: Java Windows CI

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 11
          java-package: jdk
          architecture: x64

      - uses: ilammy/msvc-dev-cmd@v1

      - name: Build with Maven
        run: mvn --batch-mode install --file pom.xml --projects applet,coreAPI,plugins/windows

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-natives
          path: plugins/windows/target/*.jar
